version: "3.8"

services:
  postgres:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_PASSWORD: example 
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080